"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
// import { body } from "express-validator";
// import User from "../models/User";
const postsControllers_1 = require("../controllers/postsControllers");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.get("/", postsControllers_1.getPosts);
router.post("/", auth_1.requireAuth, postsControllers_1.createPost);
exports.default = router;
